In [1]:
import numpy as np
import pandas as pd

In [84]:
data = pd.read_csv('pima-indians-diabetes.csv',  names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'])

In [3]:
data

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [4]:
data.isna().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [85]:
data = data.iloc[:, :-1]

In [6]:
data

preg  plas  pres  skin  test  mass   pedi  age
0       6   148    72    35     0  33.6  0.627   50
1       1    85    66    29     0  26.6  0.351   31
2       8   183    64     0     0  23.3  0.672   32
3       1    89    66    23    94  28.1  0.167   21
4       0   137    40    35   168  43.1  2.288   33
..    ...   ...   ...   ...   ...   ...    ...  ...
763    10   101    76    48   180  32.9  0.171   63
764     2   122    70    27     0  36.8  0.340   27
765     5   121    72    23   112  26.2  0.245   30
766     1   126    60     0     0  30.1  0.349   47
767     1    93    70    31     0  30.4  0.315   23

[768 rows x 8 columns]

In [7]:
data[data['skin'] == 0]

preg  plas  pres  skin  test  mass   pedi  age
2       8   183    64     0     0  23.3  0.672   32
5       5   116    74     0     0  25.6  0.201   30
7      10   115     0     0     0  35.3  0.134   29
9       8   125    96     0     0   0.0  0.232   54
10      4   110    92     0     0  37.6  0.191   30
..    ...   ...   ...   ...   ...   ...    ...  ...
757     0   123    72     0     0  36.3  0.258   52
758     1   106    76     0     0  37.5  0.197   26
759     6   190    92     0     0  35.5  0.278   66
762     9    89    62     0     0  22.5  0.142   33
766     1   126    60     0     0  30.1  0.349   47

[227 rows x 8 columns]

In [86]:
data = data.replace({'skin': 0, 'test': 0}, np.nan)

# KNNImputer

In [87]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data = imputer.fit_transform(data)

In [12]:
data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [13]:
import sys
np.set_printoptions(threshold=sys.maxsize)

# StandarScaler

In [15]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
data = scaler.fit_transform(data)

In [16]:
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.25753136e-01, -2.69421175e-01,  2.04012771e-01,
         4.68491977e-01,  1.42599540e+00],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -4.42180040e-03, -8.50042043e-01, -6.84421946e-01,
        -3.65060778e-01, -1.90671905e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         1.00607356e-01,  4.20066105e-01, -1.10325546e+00,
         6.04397318e-01, -1.05584152e-01],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -6.34596736e-01, -5.79525502e-01, -4.94043078e-01,
        -9.20762614e-01, -1.04154944e+00],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.25753136e-01,  1.52848546e-01,  1.40974560e+00,
         5.48490910e+00, -2.04963989e-02],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
        -1.12473280e+00, -4.31071303e-01, -8.11341192e-01,
        -8.18078579e-01, -2.75759658e-01],
       [-2.50952128e-01, -1.342476

# MinMaxScaler

In [23]:
from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler(feature_range= (0, 1))
data = minmaxscaler.fit_transform(data)

In [24]:
data

array([[0.35294118, 0.74371859, 0.59016393, 0.30434783, 0.1338141 ,
        0.50074516, 0.23441503, 0.48333333],
       [0.05882353, 0.42713568, 0.54098361, 0.23913043, 0.06330128,
        0.39642325, 0.11656704, 0.16666667],
       [0.47058824, 0.91959799, 0.52459016, 0.25      , 0.21754808,
        0.34724292, 0.25362938, 0.18333333],
       [0.05882353, 0.44723618, 0.54098361, 0.17391304, 0.09615385,
        0.41877794, 0.03800171, 0.        ],
       [0.        , 0.68844221, 0.32786885, 0.30434783, 0.18509615,
        0.64232489, 0.94363792, 0.2       ],
       [0.29411765, 0.58291457, 0.60655738, 0.12318841, 0.11418269,
        0.38152012, 0.05251921, 0.15      ],
       [0.17647059, 0.3919598 , 0.40983607, 0.27173913, 0.08894231,
        0.46199702, 0.07258753, 0.08333333],
       [0.58823529, 0.57788945, 0.        , 0.25362319, 0.07451923,
        0.52608048, 0.02391119, 0.13333333],
       [0.11764706, 0.98994975, 0.57377049, 0.41304348, 0.63581731,
        0.45454545, 0.034158

# Normalizer

In [34]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
data = normalizer.fit_transform(data)

In [35]:
data

array([[2.74759155e-02, 6.77739248e-01, 3.29710985e-01, 1.60276173e-01,
        5.73941345e-01, 1.53865127e-01, 2.87123316e-03, 2.28965962e-01],
       [7.34497791e-03, 6.24323123e-01, 4.84768542e-01, 2.13004360e-01,
        4.89665194e-01, 1.95376413e-01, 2.57808725e-03, 2.27694315e-01],
       [2.86186772e-02, 6.54652240e-01, 2.28949417e-01, 1.07320039e-01,
        6.97580256e-01, 8.33518972e-02, 2.40396888e-03, 1.14474709e-01],
       [6.61199291e-03, 5.88467369e-01, 4.36391532e-01, 1.52075837e-01,
        6.21527334e-01, 1.85797001e-01, 1.10420282e-03, 1.38851851e-01],
       [0.00000000e+00, 5.96386300e-01, 1.74127387e-01, 1.52361463e-01,
        7.31335024e-01, 1.87622259e-01, 9.96008652e-03, 1.43655094e-01],
       [2.76375946e-02, 6.41192195e-01, 4.09036401e-01, 1.01337847e-01,
        6.02499563e-01, 1.41504485e-01, 1.11103130e-03, 1.65825568e-01],
       [2.17653979e-02, 5.65900344e-01, 3.62756631e-01, 2.32164244e-01,
        6.38451670e-01, 2.24909111e-01, 1.79927289e-03, 1.

# Normalizer & StandardScaler

In [36]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
data = scaler.fit_transform(data)

In [37]:
data

array([[ 5.06640829e-01,  8.30826948e-01, -1.08681357e-01,
         2.82271288e-01, -3.79069545e-01, -1.00061137e-01,
         3.13315025e-01,  1.06926313e+00],
       [-6.70708963e-01,  3.95482805e-01,  1.02689364e+00,
         1.19857607e+00, -8.90941522e-01,  6.23252946e-01,
         1.41224287e-01,  1.04844927e+00],
       [ 5.73474788e-01,  6.42666656e-01, -8.46615834e-01,
        -6.37994755e-01,  3.71881858e-01, -1.32872006e+00,
         3.90084394e-02, -8.04689318e-01],
       [-7.13577296e-01,  1.03256584e-01,  6.72601179e-01,
         1.39766715e-01, -9.00443127e-02,  4.56336329e-01,
        -7.24016691e-01, -4.05692849e-01],
       [-1.10027704e+00,  1.67796272e-01, -1.24810885e+00,
         1.44730301e-01,  5.76899767e-01,  4.88140575e-01,
         4.47481254e+00, -3.27075063e-01],
       [ 5.16096571e-01,  5.32966607e-01,  4.72263936e-01,
        -7.41952655e-01, -2.05614169e-01, -3.15439346e-01,
        -7.20008040e-01,  3.58034300e-02],
       [ 1.72663502e-01, -8.066581

# Normalizer & MinMaxScaler

In [46]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
data = normalizer.fit_transform(data)

from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler(feature_range= (0, 1))
data = minmaxscaler.fit_transform(data)

In [47]:
data

array([[0.42839521, 0.74411023, 0.45688815, 0.47442369, 0.44166368,
        0.5130297 , 0.27140048, 0.50765699],
       [0.11107434, 0.66483652, 0.65154094, 0.63194279, 0.35747907,
        0.63183729, 0.23379445, 0.48919455],
       [0.4936336 , 0.79514809, 0.35097707, 0.32804661, 0.6072309 ,
        0.30745427, 0.24672077, 0.23439622],
       [0.10923956, 0.68462405, 0.64077847, 0.47352527, 0.51173413,
        0.65644166, 0.0937147 , 0.29124537],
       [0.        , 0.58691841, 0.21628131, 0.40141624, 0.51824304,
        0.56074074, 0.90117309, 0.25748772],
       [0.45998998, 0.75148197, 0.60505399, 0.29508866, 0.49790283,
        0.50364927, 0.09516262, 0.36778547],
       [0.32307295, 0.5915019 , 0.47855668, 0.6815544 , 0.47373387,
        0.71392224, 0.15271087, 0.38409943],
       [0.87421992, 0.707947  , 0.        , 0.51799053, 0.32279853,
        0.65994126, 0.05621009, 0.350158  ],
       [0.06607946, 0.45833701, 0.20555052, 0.24077388, 0.9281889 ,
        0.21549947, 0.002474

# MinMaxScaler & Normalizer

In [55]:
from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler(feature_range= (0, 1))
data = minmaxscaler.fit_transform(data)

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
data = normalizer.fit_transform(data)

In [57]:
data

array([[0.27263947, 0.57450662, 0.45588895, 0.23510215, 0.10336852,
        0.38681487, 0.18108057, 0.37336461],
       [0.06846077, 0.49711461, 0.62961459, 0.2783079 , 0.07367212,
        0.46137047, 0.13566457, 0.19397217],
       [0.364081  , 0.71146734, 0.40586079, 0.19341803, 0.16831088,
        0.26865217, 0.19622598, 0.14183989],
       [0.06969035, 0.52985678, 0.64092272, 0.20604103, 0.11391692,
        0.49614128, 0.04502199, 0.        ],
       [0.        , 0.480668  , 0.22891691, 0.21249461, 0.1292335 ,
        0.44846905, 0.65884477, 0.13963932],
       [0.29511752, 0.58489623, 0.60861941, 0.12360719, 0.11457086,
        0.38281712, 0.05269776, 0.15050994],
       [0.21719601, 0.48241526, 0.50441697, 0.33445038, 0.10946818,
        0.56861549, 0.08933909, 0.10256478],
       [0.57544021, 0.5653194 , 0.        , 0.24810647, 0.07289832,
        0.51463736, 0.02339108, 0.13043311],
       [0.07609724, 0.64032579, 0.37113   , 0.26716749, 0.41126352,
        0.29401207, 0.022094

# MinMaxScaler & StandardScaler****

In [74]:
from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler(feature_range= (0, 1))
data = minmaxscaler.fit_transform(data)

from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
data = scaler.fit_transform(data)

# دیتا خروجی در این حالت هیچ فرقی با حالت استاندارد ندارد

In [75]:
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.25753136e-01, -2.69421175e-01,  2.04012771e-01,
         4.68491977e-01,  1.42599540e+00],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -4.42180040e-03, -8.50042043e-01, -6.84421946e-01,
        -3.65060778e-01, -1.90671905e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         1.00607356e-01,  4.20066105e-01, -1.10325546e+00,
         6.04397318e-01, -1.05584152e-01],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -6.34596736e-01, -5.79525502e-01, -4.94043078e-01,
        -9.20762614e-01, -1.04154944e+00],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.25753136e-01,  1.52848546e-01,  1.40974560e+00,
         5.48490910e+00, -2.04963989e-02],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
        -1.12473280e+00, -4.31071303e-01, -8.11341192e-01,
        -8.18078579e-01, -2.75759658e-01],
       [-2.50952128e-01, -1.342476

# StandardScaler & MinMaxScaler*****

In [82]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
data = scaler.fit_transform(data)

from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler(feature_range= (0, 1))
data = minmaxscaler.fit_transform(data)

# دیتا خروجی در این حالت هیچ فرقی با حالت مینیمم و ماکسیمم ندارد

In [83]:
data

array([[0.35294118, 0.74371859, 0.59016393, 0.30434783, 0.1338141 ,
        0.50074516, 0.23441503, 0.48333333],
       [0.05882353, 0.42713568, 0.54098361, 0.23913043, 0.06330128,
        0.39642325, 0.11656704, 0.16666667],
       [0.47058824, 0.91959799, 0.52459016, 0.25      , 0.21754808,
        0.34724292, 0.25362938, 0.18333333],
       [0.05882353, 0.44723618, 0.54098361, 0.17391304, 0.09615385,
        0.41877794, 0.03800171, 0.        ],
       [0.        , 0.68844221, 0.32786885, 0.30434783, 0.18509615,
        0.64232489, 0.94363792, 0.2       ],
       [0.29411765, 0.58291457, 0.60655738, 0.12318841, 0.11418269,
        0.38152012, 0.05251921, 0.15      ],
       [0.17647059, 0.3919598 , 0.40983607, 0.27173913, 0.08894231,
        0.46199702, 0.07258753, 0.08333333],
       [0.58823529, 0.57788945, 0.        , 0.25362319, 0.07451923,
        0.52608048, 0.02391119, 0.13333333],
       [0.11764706, 0.98994975, 0.57377049, 0.41304348, 0.63581731,
        0.45454545, 0.034158

# StandardScaler & Normalizer

In [91]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
data = scaler.fit_transform(data)

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
data = normalizer.fit_transform(data)

In [92]:
data

array([[ 3.23622755e-01,  4.28999232e-01,  7.56736619e-02,
         3.16444754e-01, -1.36246888e-01,  1.03169713e-01,
         2.36917436e-01,  7.21129052e-01],
       [-4.60766646e-01, -6.12655617e-01, -8.75552539e-02,
        -2.41147377e-03, -4.63579063e-01, -3.73256461e-01,
        -1.99089603e-01, -1.03984860e-01],
       [ 4.61432702e-01,  7.26892103e-01, -9.87057934e-02,
         3.76240129e-02,  1.57091621e-01, -4.12583128e-01,
         2.26025745e-01, -3.94851795e-02],
       [-3.91751521e-01, -4.62843335e-01, -7.44409434e-02,
        -2.94246224e-01, -2.68711105e-01, -2.29075099e-01,
        -4.26933999e-01, -4.82939749e-01],
       [-1.89497221e-01,  8.36510329e-02, -2.49712022e-01,
         1.03847548e-01,  2.53661482e-02,  2.33955878e-01,
         9.10254106e-01, -3.40150235e-03],
       [ 1.96083631e-01, -8.75764563e-02,  1.44661939e-01,
        -6.43014691e-01, -2.46445361e-01, -4.63847330e-01,
        -4.67699124e-01, -1.57653010e-01],
       [-1.22479452e-01, -6.552077